apiVersion: v1
kind: Pod
metadata:
  name: sysbench
  labels:
    app: sysbench
    owner: VIPULDHINGRA  # Add the owner name as a label
spec:
  containers:
  - name: sysbench
    image: severalnines/sysbench
    command: ["/bin/sh"]
    args:
      - "-c"
      - |
        sysbench --threads=${THREADS} --time=${TIME} ${TEST} run;
        exec /bin/sh -c 'while true; do sleep 3600; done'
    env:
      - name: THREADS
        value: "4"
      - name: TIME
        value: "60"
      - name: TEST
        value: "cpu"
    resources:
      limits:
        memory: "512Mi"
        cpu: "1"
    tty: true
    stdin: true
